### ISSUE TITLE
OffsetLoop errors when selecting only one edge

### ISSUE THREAD

**Issue by thomthom** [thomthom/quadface-tools#103]
**[Original report](https://bitbucket.org/thomthom/quadface-tools/issue/103) by me.**

----------------------------------------

```
#<ArgumentError: Not enough points: at least 2 required>
C:/Users/max/AppData/Roaming/SketchUp/SketchUp 2016/SketchUp/Plugins/TT_QuadFaceTools/controllers/loop_offset.rb:267:in `draw'
C:/Users/max/AppData/Roaming/SketchUp/SketchUp 2016/SketchUp/Plugins/TT_QuadFaceTools/controllers/loop_offset.rb:267:in `draw'
C:/Users/max/AppData/Roaming/SketchUp/SketchUp 2016/SketchUp/Plugins/TT_QuadFaceTools/tools/offset.rb:159:in `draw'
```

**Comment by thomthom** [comment]
https://github.com/thomthom/quadface-tools/blob/1.0/src/TT_QuadFaceTools/controllers/loop_offset.rb#L267
