### ISSUE TITLE
Crash on import

### ISSUE THREAD

**Issue by thomthom** [thomthom/quadface-tools#105]
**[Original report](https://bitbucket.org/thomthom/quadface-tools/issue/105) by Duane Kemp (Bitbucket: [duanekemp](https://bitbucket.org/duanekemp), GitHub: [duanekemp](https://github.com/duanekemp)).**

The original report had attachments: 靠枕_01.obj, 靠枕_01.mtl

[靠枕_01.zip](https://github.com/thomthom/quadface-tools/files/2799062/U.y.i.A.u._01.zip)

----------------------------------------

Quad version 0.12.0

coplaner- not selected

Scale- inches

http://sketchup.thomthom.net/extensions/TT_QuadFaceTools/reports/report/4925

```
#<ArgumentError: invalid byte sequence in UTF-8>
C:/Users/Duane/AppData/Roaming/SketchUp/SketchUp 2016/SketchUp/Plugins/TT_QuadFaceTools/importers/obj.rb:125:in `split'
C:/Users/Duane/AppData/Roaming/SketchUp/SketchUp 2016/SketchUp/Plugins/TT_QuadFaceTools/importers/obj.rb:125:in `block (2 levels) in load_file'
C:/Users/Duane/AppData/Roaming/SketchUp/SketchUp 2016/SketchUp/Plugins/TT_QuadFaceTools/importers/obj.rb:119:in `each_line'
C:/Users/Duane/AppData/Roaming/SketchUp/SketchUp 2016/SketchUp/Plugins/TT_QuadFaceTools/importers/obj.rb:119:in `block in load_file'
C:/Users/Duane/AppData/Roaming/SketchUp/SketchUp 2016/SketchUp/Plugins/TT_QuadFaceTools/importers/obj.rb:118:in `open'
C:/Users/Duane/AppData/Roaming/SketchUp/SketchUp 2016/SketchUp/Plugins/TT_QuadFaceTools/importers/obj.rb:118:in `load_file'
```

**Comment by thomthom** [comment]
Fixed in c238786

**Comment by thomthom** [comment]
**Original comment by Duane Kemp (Bitbucket: [duanekemp](https://bitbucket.org/duanekemp), GitHub: [duanekemp](https://github.com/duanekemp)).**

----------------------------------------

Thomas, You are the man!

**Comment by thomthom** [comment]
Should appear in v 0.13.0

**Comment by thomthom** [comment]
**Original comment by Duane Kemp (Bitbucket: [duanekemp](https://bitbucket.org/duanekemp), GitHub: [duanekemp](https://github.com/duanekemp)).**

----------------------------------------

Looking forward to that. Can't wait to see the improvements and test your addition to this. Very cool, Thomas. Very cool.
