### ISSUE TITLE
Cancelling import cause an error

### ISSUE THREAD

**Issue by thomthom** [thomthom/quadface-tools#114]
**[Original report](https://bitbucket.org/thomthom/quadface-tools/issue/114) by me.**

----------------------------------------

```
Error: #<NoMethodError: undefined method `each' for nil:NilClass>
C:/Users/Thomas/SourceTree/quadface-tools/src/TT_QuadFaceTools/importers/obj.rb:523:in `process_options'
C:/Users/Thomas/SourceTree/quadface-tools/src/TT_QuadFaceTools/importers/obj.rb:80:in `do_options'
```

**Comment by thomthom** [comment]
Fix error occuring after cancelling OBJ Import options. Fixes #114
