### ISSUE TITLE
Reading the Settings produces nil errors

### ISSUE THREAD

**Issue by thomthom** [thomthom/quadface-tools#42]
**[Original report](https://bitbucket.org/thomthom/quadface-tools/issue/42) by me.**

The original report had attachments: QuadFace_reload.png

![quadface_reload](https://user-images.githubusercontent.com/192418/51788135-ef897300-217a-11e9-805e-b77f6959271c.png)

----------------------------------------

Several reports of loading errors that seem to be related to reading the settings. Nils are encountered... Might be related to UV Tools not reporting / handling errors when invalid grids are encountered?

**Comment by thomthom** [comment]
http://forums.sketchucation.com/viewtopic.php?f=323&t=39442&start=60#p358506

    
    #!ruby
    TT::Lib::VERSION 2.5.8
    When I write load 'tt_quadface.rb' , ruby console generates the following message:
    load 'tt_quadface.rb'
    C:/Archivos de programa/Google/Google SketchUp 8/Plugins/tt_quadface.rb:20: warning: already initialized constant PLUGIN
    C:/Archivos de programa/Google/Google SketchUp 8/Plugins/tt_quadface.rb:21: warning: already initialized constant PLUGIN_ID
    C:/Archivos de programa/Google/Google SketchUp 8/Plugins/tt_quadface.rb:22: warning: already initialized constant PLUGIN_NAME
    C:/Archivos de programa/Google/Google SketchUp 8/Plugins/tt_quadface.rb:24: warning: already initialized constant PLUGIN_VERSION
    C:/Archivos de programa/Google/Google SketchUp 8/Plugins/tt_quadface.rb:27: warning: already initialized constant PATH_ROOT
    C:/Archivos de programa/Google/Google SketchUp 8/Plugins/tt_quadface.rb:28: warning: already initialized constant PATH
    C:/Archivos de programa/Google/Google SketchUp 8/Plugins/tt_quadface.rb:29: warning: already initialized constant PATH_ICONS
    Error: #<NoMethodError: C:/Archivos de programa/Google/Google SketchUp 8/Plugins/TT_Lib2/settings.rb:51:in `[]': undefined method `to_l' for nil:NilClass>
    (eval)
    C:/Archivos de programa/Google/Google SketchUp 8/Plugins/TT_Lib2/settings.rb:90:in `set_default'
    C:/Archivos de programa/Google/Google SketchUp 8/Plugins/TT_QuadFaceTools/core.rb:45
    C:/Archivos de programa/Google/Google SketchUp 8/Tools/extensions.rb:36:in `require'
    C:/Archivos de programa/Google/Google SketchUp 8/Tools/extensions.rb:36:in `load'
    C:/Archivos de programa/Google/Google SketchUp 8/Plugins/tt_quadface.rb:41:in `register_extension'
    C:/Archivos de programa/Google/Google SketchUp 8/Plugins/tt_quadface.rb:41
    (eval):0:in `load'
    (eval):0
    

http://forums.sketchucation.com/viewtopic.php?f=323&t=39442&start=75#p358911
( See attached file: QuadFace_reload.png )

**Comment by thomthom** [comment]
Hotpatched in <<changeset 1fc94ae97350>>

The UV Mapping tool wrote nils if it was cancelled before U and V was picked. This was because the settings where not loaded until after V was picked.

Just to be sure no other error linger around, error catching was added around the loading of the UV Scale settings that resets U and V to 1.0.

**Comment by thomthom** [comment]
Is this related?

https://extensions.sketchup.com/en/comment/107066#comment-107066

Don't understand why the error is not rescued. Older version?

```
Error: #<NameError: uninitialized constant Infinity>
<main>:in `<main>'
C:/Users/User/AppData/Roaming/SketchUp/SketchUp 2018/SketchUp/Plugins/TT_Lib2/settings.rb:51:in `eval'
C:/Users/User/AppData/Roaming/SketchUp/SketchUp 2018/SketchUp/Plugins/TT_Lib2/settings.rb:51:in `read_default'
C:/Users/User/AppData/Roaming/SketchUp/SketchUp 2018/SketchUp/Plugins/TT_Lib2/settings.rb:51:in `[]'
C:/Users/User/AppData/Roaming/SketchUp/SketchUp 2018/SketchUp/Plugins/TT_Lib2/settings.rb:96:in `set_default'
C:/Users/User/AppData/Roaming/SketchUp/SketchUp 2018/SketchUp/Plugins/TT_QuadFaceTools/core.rb:63:in `<module:QuadFaceTools>'
C:/Users/User/AppData/Roaming/SketchUp/SketchUp 2018/SketchUp/Plugins/TT_QuadFaceTools/core.rb:35:in `<top (required)>'
C:/Program Files/SketchUp/SketchUp 2018/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Program Files/SketchUp/SketchUp 2018/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Users/User/AppData/Roaming/SketchUp/SketchUp 2018/SketchUp/Plugins/TT_QuadFaceTools/bootstrap.rb:35:in `<top (required)>'
C:/Program Files/SketchUp/SketchUp 2018/Tools/extensions.rb:197:in `require'
C:/Program Files/SketchUp/SketchUp 2018/Tools/extensions.rb:197:in `load'
C:/Users/User/AppData/Roaming/SketchUp/SketchUp 2018/SketchUp/Plugins/TT_QuadFaceTools.rb:54:in `register_extension'
C:/Users/User/AppData/Roaming/SketchUp/SketchUp 2018/SketchUp/Plugins/TT_QuadFaceTools.rb:54:in `<module:QuadFaceTools>'
C:/Users/User/AppData/Roaming/SketchUp/SketchUp 2018/SketchUp/Plugins/TT_QuadFaceTools.rb:15:in `<module:Plugins>'
C:/Users/User/AppData/Roaming/SketchUp/SketchUp 2018/SketchUp/Plugins/TT_QuadFaceTools.rb:14:in `<module:TT>'
C:/Users/User/AppData/Roaming/SketchUp/SketchUp 2018/SketchUp/Plugins/TT_QuadFaceTools.rb:13:in `<top (required)>'
```

**Comment by thomthom** [comment]
Possible workaround for users:

```
TT::Plugins::QuadFaceTools.settings[ :uv_u_scale ] = 1.0
TT::Plugins::QuadFaceTools.settings[ :uv_v_scale ] = 1.0
```

**Comment by thomthom** [comment]
The issue appear to still exist: https://forums.sketchup.com/t/quadface-tools-error-when-su-starts/95930

**Comment by wrc86** [comment]
Hello, got the same problem on sketchup Version 20.2.171 Mac.
fixed with:
TT::Plugins::QuadFaceTools.settings[ :uv_u_scale ] = 1.0
TT::Plugins::QuadFaceTools.settings[ :uv_v_scale ] = 1.0

Error: #<NameError: uninitialized constant Infinity>

:in <main>' /Users/id/Library/Application Support/SketchUp 2020/SketchUp/Plugins/TT_Lib2/settings.rb:51:in eval' /Users/jid/Library/Application Support/SketchUp 2020/SketchUp/Plugins/TT_Lib2/settings.rb:51:in read_default' /Users/id/Library/Application Support/SketchUp 2020/SketchUp/Plugins/TT_Lib2/settings.rb:51:in []' /Users/id/Library/Application Support/SketchUp 2020/SketchUp/Plugins/TT_Lib2/settings.rb:96:in set_default' /Users/id/Library/Application Support/SketchUp 2020/SketchUp/Plugins/TT_QuadFaceTools/core.rb:63:in module:QuadFaceTools' /Users/id/Library/Application Support/SketchUp 2020/SketchUp/Plugins/TT_QuadFaceTools/core.rb:35:in <top (required)>' /Applications/SketchUp 2020/SketchUp.app/Contents/Frameworks/Ruby.framework/Versions/2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in require' /Applications/SketchUp 2020/SketchUp.app/Contents/Frameworks/Ruby.framework/Versions/2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in require' /Users/id/Library/Application Support/SketchUp 2020/SketchUp/Plugins/TT_QuadFaceTools/bootstrap.rb:35:in <top (required)>' /Applications/SketchUp 2020/SketchUp.app/Contents/Resources/Content/Tools/extensions.rb:197:in require' /Applications/SketchUp 2020/SketchUp.app/Contents/Resources/Content/Tools/extensions.rb:197:in load' /Users/id/Library/Application Support/SketchUp 2020/SketchUp/Plugins/TT_QuadFaceTools.rb:54:in register_extension' /Users/id/Library/Application Support/SketchUp 2020/SketchUp/Plugins/TT_QuadFaceTools.rb:54:in module:QuadFaceTools' /Users/id/Library/Application Support/SketchUp 2020/SketchUp/Plugins/TT_QuadFaceTools.rb:15:in <module:Plugins>' /Users/id/Library/Application Support/SketchUp 2020/SketchUp/Plugins/TT_QuadFaceTools.rb:14:in module:TT' /Users/id/Library/Application Support/SketchUp 2020/SketchUp/Plugins/TT_QuadFaceTools.rb:13:in `<top (required)>'

**Comment by thomthom** [comment]
Another report: https://forums.sketchup.com/t/tt-lib2-tt-quadface-load-errors/152707/5?u=tt_su

```
Error: #<NameError: uninitialized constant Infinity>

:in `' C:/Users/oshri/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/TT_Lib2/settings.rb:51:in `eval' C:/Users/oshri/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/TT_Lib2/settings.rb:51:in `read_default' C:/Users/oshri/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/TT_Lib2/settings.rb:51:in `[]' C:/Users/oshri/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/TT_Lib2/settings.rb:96:in `set_default' C:/Users/oshri/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/TT_QuadFaceTools/core.rb:63:in `' C:/Users/oshri/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/TT_QuadFaceTools/core.rb:35:in `' C:/Program Files/SketchUp/SketchUp 2021/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:72:in `require' C:/Program Files/SketchUp/SketchUp 2021/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:72:in `require' C:/Users/oshri/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/TT_QuadFaceTools/bootstrap.rb:35:in `' C:/Program Files/SketchUp/SketchUp 2021/Tools/extensions.rb:197:in `require' C:/Program Files/SketchUp/SketchUp 2021/Tools/extensions.rb:197:in `load' C:/Users/oshri/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/TT_QuadFaceTools.rb:54:in `register_extension' C:/Users/oshri/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/TT_QuadFaceTools.rb:54:in `' C:/Users/oshri/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/TT_QuadFaceTools.rb:15:in `' C:/Users/oshri/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/TT_QuadFaceTools.rb:14:in `' C:/Users/oshri/AppData/Roaming/SketchUp/SketchUp 2021/SketchUp/Plugins/TT_QuadFaceTools.rb:13:in `'
```

**Comment by thomthom** [comment]
Complication comes from SU that captures and dump the error in the console and startup error dialog without allowing it to be rescued. (Related to `Sketchup.read_default`)
